version: "3"

services:
  pyftpd:
    image: xaled/pyftpd:1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "${PROJECT_NAME}-pyftpd"
    environment:
      - PYFTPD_DEBUG
      - PYFTPD_USERNAME
      - PYFTPD_PASSWORD
      - PYFTPD_READWRITE
      - PYFTPD_NAT_ADDRESS
    ports:
      - "${PYFTPD_DATA_PORT-0.0.0.0:20}:20"
      - "${PYFTPD_CONTROL_PORT-0.0.0.0:21}:21"
      - "${PYFTPD_PASV_PORTS-0.0.0.0:21100-21110}:21100-21110"
    volumes:
      - "./app:/app"
      - "${PYFTPD_ROOT-./data}:/data"
      - "${PYFTPD_LOGS-./logs}:/var/log/pyftpd"
    restart: unless-stopped